["pyproject.toml".tool.black]
exclude = '''
/(
    _build
  | \.eggs
  | \.git
  | \.runway
  | \.serverless
  | \.tox
  | \.venv
  | build
  | dist
  | node_modules
)/
'''
include = '\.pyi?$'
line-length = 88
target-version = ["py38", "py39"]
