["poetry.toml".virtualenvs]
in-project = true

["pyproject.toml".tool.poetry.dependencies]
python = "^3.8"

["pyproject.toml".tool.poetry.dev-dependencies]
black = "^20.8b1"
coverage = "^5.5"
flake8 = "^3.9.0"
flake8-docstrings = "^1.5.0"  # flake8 extension
isort = "^5.7.0"
mock = "^4.0.3"
nitpick = "^0.26.0"  # flake8 extension
pep8-naming = "^0.11.1"  # flake8 extension
pre-commit = "^2.10.1"
pydocstyle = "^5.1.1"  # flake8 extension
pylint = "^2.7.1"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.1"

["pyproject.toml".build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
