[".editorconfig"]
root = true

[".editorconfig"."*"]
end_of_line = "lf"
indent_size = 4
indent_style = "space"
insert_final_newline = true
trim_trailing_whitespace = true

[".editorconfig"."*.{html,js,jsx,rst,toml,ts,xml,yml,yaml}"]
indent_size = 2

[".editorconfig"."*.py"]
charset = "utf-8"

[".editorconfig".Makefile]
indent_style = "tab"

[".editorconfig"."{package,package-lock}.json"]
indent_size = 2
